name: Node.js CI/CD

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Adjust the version as needed
        
      - name: Install dependencies
        run: |
          npm install -g @angular/cli
      
      - name: Debugging
        run: |
          echo "Deploy server: ${{ secrets.DEPLOY_SERVER }}"
          echo "Private key:"
          echo "${{ secrets.PRIVATE_KEY }}"
          echo "${{ secrets.PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem
          ssh-keygen -y -f key.pem
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem admin@${{ secrets.DEPLOY_SERVER }} "rm -rf $CI_PROJECT_NAME && git clone $CI_REPOSITORY_URL && cd $CI_PROJECT_NAME && npm install && sudo systemctl reload nginx" || exit 1
