name: Node.js CI/CD

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Adjust the version as needed
        
      - name: Install dependencies
        run: |
          npm install -g @angular/cli
      
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_SERVER }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            cd $GITHUB_REPOSITORY
            git pull
            sudo systemctl reload nginx
        env:
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
          DEPLOY_USERNAME: ${{ secrets.DEPLOY_USERNAME }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}
          GITHUB_REPOSITORY: ${{ github.repository }}
